name: example_dbt_project
profile: pragunbhutani
config-version: 2
version: 1.6.4

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  # Applies to all files under models/
  materialized: table

  example-dbt-project:
    core:
      +schema: core

      facts:
        materialized: table

      dimensions:
        materialized: table

    staging:
      +schema: staging
      materialized: view

    intermediates:
      +schema: prep
      materialized: table

    snaoshots:
      +schema: prep
      materialized: table

    marts:
      +schema: mart
      materialized: table

on-run-end:
  - "grant usage on {{ this }} to role DB_ADMIN_ROLE;"
  - "grant select on {{ this }} to role DB_READER_ROLE;"
